### ISSUE TITLE
Aggiungere domande

### ISSUE THREAD

**Issue by fmanto01** [Cleo-Tech/ScopriMi#79]
Apro un issue perchè è più comodo. Vanno aggiunte domande.

**Comment by pesto13** [comment]
ok negro

**Comment by simomux** [comment]
[https://www.youtube.com/watch?v=6g5ZF6DUrHI](https://www.youtube.com/watch?v=6g5ZF6DUrHI)

**Comment by fmanto01** [comment]
Chief Keef ambassador di Cleo Tech

**Comment by simomux** [comment]
aggiungere anche domande testuali e risposte decenti
